### ISSUE TITLE
vsdocker.imageUser unknown configuration setting

### ISSUE THREAD

**Issue by pvandorp** [brendandburns/vs-kubernetes#19]
When I try to override the "vsdocker.imageUser": "docker.io/pvandorp" setting, a green squiggly appears under it telling me it is an 'unknown configration setting'.

When I do CTRL+SHIFT+P => Kubernetes Run, the image is build successfully, but I get an error saying: 'Image push failed.'

**Comment by bnookala** [comment]
@pvandorp looking at the code, it appears that that `vsdocker.imageUser` wasn't added to the contribution manifest, making it immediately fail when it tries to look up the user. I'll fix this and open a PR.

**Comment by pvandorp** [comment]
@bnookala Thanks. I'll need to figure out how these extensions in VS Code work, so I can do it myself next time :-).

**Comment by pvandorp** [comment]
@bnookala  I changed my package.json in the extension locally like you did. Now, I don't see the green squiggly anymore, but the image push still fails. Is there some sort of logging that I can look at to troubleshoot this issue?

**Comment by bnookala** [comment]
@pvandorp if I'm looking at the code correctly, you should be seeing the error output from docker in VS Code itself. Can you try this again, and show me the output from the 'Docker' channel? There's a drop down list that shows when you select the `Output` tab:

![screen shot 2017-03-27 at 2 21 21 pm](https://cloud.githubusercontent.com/assets/87996/24378707/c8df4e24-12f8-11e7-858e-30cc5c9d9c03.png)

**Comment by pvandorp** [comment]
@bnookala I don't see a Docker channel in my Output window. I only see 'Extensions', 'Git' and 'Tasks'
