### ISSUE TITLE
kubernetes debug appears to be broken...

### ISSUE THREAD

**Issue by brendandburns** [brendandburns/vs-kubernetes#24]
When I try it, the kubectl command to deploy the debug container doesn't work properly...

@itowlson

**Comment by itowlson** [comment]
@brendandburns I see an extraneous space where `_doDebug` composes the `runCmd`: `--image=` _space_ `${image}`.  Will test that's the issue and send a PR, hopefully this evening.

**Comment by itowlson** [comment]
Couple of other things had gotten borked too.  Sent #25.
