### ISSUE TITLE
Publishing to Marketplace?

### ISSUE THREAD

**Issue by oshalygin** [brendandburns/vs-kubernetes#3]
As well as a README update on how to install it?  Currently not on the marketplace 👍 

![image](https://cloud.githubusercontent.com/assets/7675942/20645990/39adc55a-b425-11e6-8cbb-e5209a538d95.png)

**Comment by ams0** [comment]
_cd_ into the extension folder:

**Windows** %USERPROFILE%\.vscode\extensions
**Mac** ~/.vscode/extensions
**Linux** ~/.vscode/extensions

(if you use Insider, use _.vscode-insider_),

`git clone https://github.com/brendandburns/vs-kubernetes.git`

restart VSCode.

**Comment by oshalygin** [comment]
thanks @ams0
