### ISSUE TITLE
Microsoft's Kubernetes Extension Replacing this Extension?

### ISSUE THREAD

**Issue by sgtoj** [brendandburns/vs-kubernetes#42]
Microsoft manages [vscode-kubernetes-tools](https://github.com/Azure/vscode-kubernetes-tools). Based on the `README` alone, there seems to be very similar between this project and their project.  Additionally, I noticed that this project's primary contributors, @itowlson and yourself (@brendandburns), are contributing to their project. Naturally, I am wondering if this projects is being replacing by the Microsoft managed project.  If so, should the `README` to redirect to the Microsoft's managed project?

**Comment by itowlson** [comment]
Yes, the Microsoft extension supersedes this one - indeed the initial release of the Microsoft extension was pretty much just merging this extension with the Helm extension. New development will happen on the Microsoft extension, and we'll update Brendan's to load the new one. Good point about the `README` - I'll send Brendan a PR!
