### ISSUE TITLE
[Feature Request] Provide "open new shell" command

### ISSUE THREAD

**Issue by lostintangent** [brendandburns/vs-kubernetes#5]
It would be cool to have a command which allowed easily starting a new shell session within a specified pod/container. The command could prompt you with a list of running pods (inside the currently configured namespace), and would simply forward something like `kubectl exec -it <POD> /bin/sh` to the VS Code integrated terminal.

The Docker extension for VS Code provides a [similar experience](https://github.com/Microsoft/vscode-docker/blob/master/commands/open-shell-container.ts), which can be pretty handy for diagnosing something quickly, without needing to leave the IDE.

**Comment by brendandburns** [comment]
yep, it's now added:

https://github.com/brendandburns/vs-kubernetes/commit/cf4430e27d8c3196906805bcf66019c4f8006e61

Now pushed as version 0.0.5
